---
- name: Install ftp
  yum:
    update_cache: yes
    name: vsftpd
    state: present

- name: check started status
  service:
    name: vsftpd
    state: started
    enabled: yes

- name: Configuring vsftpd
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart vsftpd


- name: Create a directory for upload
  file:
    path: "{{ anonymous_upload_path_dir }}"
    state: directory
    mode: '0755'
    owner: ftp

- name: Set ftpd_anon_write flag on and keep it persistent across reboots
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes

- name: Allow to write files in /var/ftp/pub/upload
  sefcontext:
    target: "{{ anonymous_upload_path_dir }}"
    setype: public_content_rw_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: restorecon -F -R -v "{{ anonymous_upload_path_dir }}"