---
# inner.yml
- name: create users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.email }}"
    create_home: "{{ item.is_create_home }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: on_create
    state: present
  loop: "{{ users }}"
  when: outer_item == item.name


# - name: create users
#   user:
#     name: "{{ item.name }}"
#     comment: "{{ item.email }}"
#     create_home: "{{ item.is_create_home }}"
#     password: "{{ item.password | password_hash('sha512') }}"
#     update_password: on_create
#     state: present
#   loop: "{{ users }}"
