---
#tasks file for create_userd
- name: Add vars
  include_vars:
    dir: vars

- include_tasks: inner.yml
  loop:
    - carol
  loop_control:
    loop_var: outer_item

- name: ansible_distribution
  debug:
    msg: "{{ ansible_distribution }}"


- name: ansible_distribution_release
  debug:
    msg: "{{ ansible_distribution_release }}"

- name: System details
  debug:
    msg: "{{ ansible_facts['lsb']['release'] }}"

# - name: ubuntu 18
#   shell: echo "hello 18"
#   register: ub18
#   when: ansible_facts['lsb']['release'] == "18.04"

# - debug:
#     msg: "{{ ub18 }}"

# - name: ubuntu 20
#   shell: echo "hello 20"
#   register: ub20
#   when: ansible_facts['lsb']['release'] == "20.04"

# - debug:
#     msg: "{{ ub20 }}"



# - name: create users
#   user:
#     name: "{{ item.name }}"
#     comment: "{{ item.email }}"
#     create_home: "{{ item.is_create_home }}"
#     password: "{{ item.password | password_hash('sha512') }}"
#     update_password: on_create
#     state: present
#   loop: "{{ users }}"