---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# tasks file for install_apache
- name: Uninstall apache
  yum:
    name: "{{ apache_service }}"
    state: absent

- include_tasks: delete-index-file.yml

- include_tasks: close-firewalld.yml
  when: ansible_os_family == 'RedHat'
