---
- name: inatsll Python
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: inatsll Python
  yum:
    name: python3-pip
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install Docker SDK for Python.
  pip:
    name: docker
    state: present
    version: latest
