---
# tasks file for ftp_install

- include_tasks: install_and_configurate_vsftpd.yml

- name: Install firewalld
  yum:
    update_cache: yes
    name: firewalld
    state: present
  notify: Start firewalld

- name: Open 20-21's port for vsftpd
  firewalld:
    service: ftp
    permanent: yes
    state: enabled
  notify: Restar firewalld